name: bio446_workcell
include:
  - path: 'docker/wei.compose.yaml'
  - path: 'docker/dashboard.compose.yaml'
services:
  ###########
  # Modules #
  ###########
  biopf400:
    container_name: biopf400
    image: ghcr.io/ad-sdl/pf400_module
    command: python -m pf400_rest_node --port 3000 --pf400_ip 146.137.240.33 --pf400_port 10100
    ports:
      - 3000:3000
