#####################
# WEI Core Services #
#####################
services:
  wei_server:
    image: ghcr.io/ad-sdl/wei:latest
    container_name: wei_server
    ports:
      - 8000:8000
    volumes:
      - ../workcells:/workcell_defs
      - ~/.wei:/home/app/.wei
    command: python3 -m wei.server --workcell /workcell_defs/bio446.workcell.yaml --server_host 0.0.0.0
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    restart: unless-stopped
    depends_on:
      - wei_redis

  wei_engine:
    image: ghcr.io/ad-sdl/wei:latest
    container_name: wei_engine
    volumes:
      - ../workcells:/workcell_defs
      - ~/.wei:/home/app/.wei
    command: python3 -m wei.engine --workcell /workcell_defs/bio446.workcell.yaml
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=1000
      - GROUP_ID=1000
    restart: unless-stopped
    depends_on:
      - wei_redis
      - wei_server

  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  redis_commander:
    image: ghcr.io/joeferner/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOST=wei_redis
